title: Networks in Science of Science
description: "A NetSci 2024 Satellite Workshop"

timezone: Europe/Vienna

navigation:
  Home: "/2024/"
  Call for Papers: "/2024/cfp"
  Accepted Papers: "/2024/papers"
  Speakers: "/2024/speakers"
  Schedule: "/2024/schedule"
  Organizers: "/2024/organizers"
  Back: "https://netscisci.github.io/"

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
